### ISSUE TITLE
Create Add Friend Component

### ISSUE THREAD

**Issue by alexkobus** [Purdue-ACM-SIGApp/mixtape-frontend#27]
![image](https://github.com/Purdue-ACM-SIGAPP/mixtape-frontend/assets/70383566/eefe6b36-e5fe-41ee-ac38-99abca85d484)

**Comment by ColinWu0403** [comment]
![Add Friend Onpress](https://github.com/Purdue-ACM-SIGAPP/mixtape-frontend/assets/85907102/e1cb7558-6a5e-4d4c-ac09-72b7c6d684a6)
![Add Friend](https://github.com/Purdue-ACM-SIGAPP/mixtape-frontend/assets/85907102/d97b6030-21f2-4d9d-bafd-feaba6ce3e71)

**Comment by ColinWu0403** [comment]
Implemented Add Friend Button
